# 线性回归
## 最小二乘法
$$
\hat{\omega} = (\omega;b)\\

\hat{x}_{i}^{T}=(x^{T}_{i};1)\\

\hat{\omega}^{*} = (X^{T}X)^{-1}X^{T}y\\

f(\hat{x}_{i}) =\hat{x}_{i}^{T} \hat{\omega}^{*}

$$

In [1]:
import numpy as np
%matplotlib qt
import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D  # 空间三维画图

In [2]:
x_1 = np.array([2,9,8,8,2,8,4,1,3,5])
x_2 = np.array([9,3,3,8,1,4,3,8,3,3])
y_raw = np.array([290,1054,944,964,246,948,488,167,370,598])

In [3]:
one = np.ones((1,len(x_1)))
X = np.vstack((x_1,x_2,one)).T
print(X.shape)
print(X)

(10, 3)
[[2. 9. 1.]
 [9. 3. 1.]
 [8. 3. 1.]
 [8. 8. 1.]
 [2. 1. 1.]
 [8. 4. 1.]
 [4. 3. 1.]
 [1. 8. 1.]
 [3. 3. 1.]
 [5. 3. 1.]]


In [4]:
y = y_raw.reshape(-1,1)
print(y.shape)
print(y)

(10, 1)
[[ 290]
 [1054]
 [ 944]
 [ 964]
 [ 246]
 [ 948]
 [ 488]
 [ 167]
 [ 370]
 [ 598]]


In [5]:
def cal_w(X,y):
    x_inv = np.linalg.inv(X.T.dot(X))
    return x_inv.dot(X.T).dot(y)
w = cal_w(X,y)
print(w)

[[114.02785464]
 [  5.02029146]
 [ 14.16941524]]


In [9]:
new_x1 = np.linspace(1,9,9)
new_x2 = np.linspace(1,9,9)
# 把两个数组的笛卡尔积内的元素的第一二个坐标分别放入两个矩阵中
x1,x2 = np.meshgrid(new_x1,new_x2)

In [11]:
# 绘制散点图
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter(x_1, x_2, y_raw)
ax.plot_surface(x1,x2,x1*w[0]+x2*w[1]+w[2],alpha=0.6)
# 添加坐标轴(顺序是Z, Y, X)
ax.set_zlabel('y', fontdict={'size': 15, 'color': 'red'})
ax.set_ylabel('x2', fontdict={'size': 15, 'color': 'red'})
ax.set_xlabel('X1', fontdict={'size': 15, 'color': 'red'})
plt.show()